
export const API_TEXT_USAGE_KEY = 'midoImageApiUsage_text';
export const API_IMAGE_USAGE_KEY = 'midoImageApiUsage_image';
export const DAILY_TEXT_LIMIT = 250;
export const DAILY_IMAGE_LIMIT = 100;
export const PROMPT_LIBRARY_KEY = 'midoImagePromptLibrary';
export const IMAGE_LIBRARY_KEY = 'midoImageLibrary';

export const LIGHTING_OPTIONS = ["Không có", "Giờ vàng", "Giờ xanh (sắc hoàng hôn mát)", "Ánh sáng ban ngày mạnh", "Trời u ám / ánh sáng tán xạ tự nhiên", "Ánh sáng mềm khi trời nhiều mây", "Ánh nắng loang lổ (xuyên qua lá/họa tiết)", "Ánh trăng", "Ánh nến", "Ánh lửa / lửa trại", "Neon", "Cực quang phương Bắc", "Phát quang sinh học (biển/ côn trùng)", "Hoàng hôn kèm lóe sáng ống kính", "U tối", "Bóng đổ kịch tính", "Tối–sáng tương phản (Chiaroscuro)", "Ánh sáng key thấp", "Ánh sáng key cao", "Ánh sáng thể tích (tia sáng, sương mờ)", "Ánh viền", "Ngược sáng", "Tạo silhouette", "Ánh sáng rìa", "Ánh sáng thực dụng (đèn/bảng hiệu trong khung)", "Neon cyberpunk", "Ánh sáng kiểu Blade Runner (neon ướt mưa)", "Đèn sân khấu", "Đèn chủ mềm", "Ánh sáng cứng", "Đèn chiếu từ trên", "Đèn chiếu từ dưới", "Ánh sáng bướm (kiểu Paramount)", "Ánh sáng Rembrandt (tam giác ở má)", "Ánh sáng chia đôi (nửa mặt sáng)", "Ánh sáng vòm/vô số (chân dung làm đẹp)", "Ánh sáng ba điểm", "Vòng đèn", "Đèn phụ phản xạ", "Đèn rọi cô lập", "Ánh sáng nền RGB LED", "Hoa văn ánh sáng hologram", "Đèn LED dây (chuyển sắc)"];
export const STYLE_OPTIONS = ["Không có", "Điện ảnh (CGI)", "Anime", "Manga", "Truyện tranh / Tiểu thuyết đồ họa", "Tranh kỹ thuật số", "Matte painting", "Minh họa giả tưởng", "Concept art", "3D phong cách Pixar", "Stop-motion / claymation CGI", "Low-poly", "Nghệ thuật isometric", "Minh họa siêu thực", "Vector tối giản", "3D tô bóng cel", "Nghệ thuật steampunk", "Phong cách Vaporwave / Synthwave", "Cyberpunk", "Nghệ thuật pixel arcade cổ điển", "Điện ảnh (nhiếp ảnh)", "Phim tài liệu / tài liệu", "Phim noir", "Nhiếp ảnh đường phố", "Nhiếp ảnh chân dung", "Thời trang biên tập", "Ánh sáng phòng chụp", "Ảnh sáng tự nhiên", "Nhiếp ảnh macro", "Nhiếp ảnh thể thao / hành động", "Nhiếp ảnh kiến trúc", "Nhiếp ảnh phong cảnh / thiên nhiên", "Đen trắng", "Tông sepia", "HDR (dải tương phản động cao)", "Phong cách ảnh Polaroid/instant", "Phim cổ điển (35mm, 16mm)", "Phong cách lố sáng / rò sáng", "Nhiếp ảnh dưới nước", "Chụp đêm / thiếu sáng"];
export const ACTION_OPTIONS = ["Không có", "Đi ra xa khỏi máy quay", "Đi về phía máy quay", "Chạy", "Chạy nước rút", "Ngồi xuống", "Đứng yên", "Quay", "Nằm (ngửa/ nghiêng/ sấp)", "Ngồi xổm", "Tựa vào tường hoặc vật thể", "Giữ thăng bằng trên bề mặt hẹp", "Vươn người/ kéo giãn", "Nhảy múa", "Nhảy mừng", "Xoay tròn", "Tạo dáng", "Diễn đạt bằng cử chỉ mạnh", "Vẫy tay", "Cúi chào", "Đồng vai / diễn lại", "Nhìn thẳng vào máy quay", "Nhìn chỗ khác (suy tư)", "Quay lưng lại", "Liếc qua vai", "Nháy mắt", "Hôn gió", "Chỉ vào máy quay", "Nói chuyện/ dẫn chuyện với người xem", "Nhìn mình trong gương", "Tương tác với vật (cầm, sử dụng, quan sát)", "Chạm vào bề mặt (tường, bàn, cây)", "Đọc sách/ giấy tờ", "Uống từ cốc/ chai", "Mở hoặc đóng cửa", "Nhặt vật trên đất", "Ném một vật", "Mang túi, hộp hoặc dụng cụ", "Khóc", "Mỉm cười ấm áp", "Cau mày", "La hét", "Thì thầm", "Thở dài", "Ngạc nhiên (tay che miệng, mắt mở to)", "Sợ hãi (lùi lại, che mặt)", "Đánh nhau (tay không hoặc có vũ khí)", "Luyện võ", "Vượt chướng ngại vật", "Leo (tường, thang, cây)", "Lái xe ô tô", "Trượt ván", "Đi xe đạp", "Cưỡi ngựa", "Bơi", "Lướt sóng", "Trượt tuyết/ ván trượt tuyết", "Ném bóng", "Tập tạ", "Khám phá môi trường xung quanh", "Quan sát xung quanh", "Đi bộ đường dài trong thiên nhiên", "Đi bộ dưới mưa", "Ngắm bầu trời hoặc các vì sao", "Theo dấu/ theo lối mòn", "Bước vào tòa nhà", "Tìm kiếm thứ gì đó", "Đào/ bới tìm một vật", "Gõ bàn phím", "Nói chuyện điện thoại", "Vẽ trên toan", "Chơi guitar", "Nấu ăn", "Ăn", "Tập luyện", "Thiền", "Hát"];
export const COMPOSITION_OPTIONS = ["Không có", "Toàn cảnh", "Viễn cảnh", "Trung cảnh", "Cận cảnh", "Siêu cận", "Góc thấp", "Góc cao", "Góc nghiêng (Dutch)", "Qua vai", "Góc nhìn người thứ nhất (FPV)", "Góc nhìn chim bay", "Góc nhìn sâu (từ dưới lên)"];
export const NSFW_OPTIONS = ["None", "Soft & Suggestive", "Sensual", "Intimate Portrait", "Boudoir", "Soft-focus Dream", "Romantic Glow", "Suggestive Tease", "Lingerie Editorial", "Playful Pin-up", "Voyeuristic Glimpse", "Erotic & Provocative", "Erotic", "Provocative", "Dark Fantasy", "Arthouse Erotic", "Taboo", "Fetish Fashion", "Striptease Moment", "Erotic Dance", "Body Worship", "Teasing Reveal", "Stylized Erotic Genres", "Gritty Realism", "Film Noir Erotic", "Neo-Noir Erotic", "Baroque Sensuality", "Giallo Erotic Horror", "FemDom Focus", "Submissive Perspective", "Roleplay Scenario (nurse, teacher, maid, etc.)"];